### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by gjhethos** [Qytera-Gmbh/JMeterHARImporterPlugin#11]
Using Windows 11 PC using Java version 8 Update 411 (build 1.80_411-b09)
With jmeter-har-import-plugin-v0.2.2.jar installed via JMeter (5.6.3) plugin manager
From Tools, Import HAR file, a file is selected but data is not imported to Jmeter

Theis error data is returned:

2024-06-18 14:22:58,766 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NoSuchMethodError: java.lang.String.formatted([Ljava/lang/Object;)Ljava/lang/String;
	at de.qytera.jmeterharimporter.HARImporter.addNewThreadGroupWithSamplers(HARImporter.java:153) ~[jmeter-har-import-plugin-v0.2.2.jar:?]
	at de.qytera.jmeterharimporter.HARImportDialog.lambda$new$4(HARImportDialog.java:228) ~[jmeter-har-import-plugin-v0.2.2.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:1.8.0_411]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:1.8.0_411]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:1.8.0_411]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:1.8.0_411]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[?:1.8.0_411]
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Component.processMouseEvent(Unknown Source) ~[?:1.8.0_411]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:1.8.0_411]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_411]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_411]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_411]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_411]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_411]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_411]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_411]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_411]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_411]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_411]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_411]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_411]

**Comment by besessener** [comment]
@gjhethos  sorry for the very late response....  can you please provide your HAR file?

**Comment by gjhethos** [comment]
The har file saved as a txt file:
[demo_har.txt](https://github.com/user-attachments/files/16270566/demo_har.txt)
I hope this can be helpful

**Comment by gjhethos** [comment]
Hello and thank you,

I have saved the har file as a text file and uploaded it  to your comment on github

Gord


Gord Holtslander (he/him/his)

Systems Administrator

[cid:e70d251b-1951-4709-9111-6350a7abd1e1]<https://www.ethoscmg.com/>    [cid:bb8db1e2-f9c7-453c-8d13-d30c34a28a02]

202-155 Skinner Street, Nanaimo, BC, V9R 5E8

***@***.***

ethoscmg.com<https://www.ethoscmg.com/>

[facebook-icon_64x64]<https://www.facebook.com/ethoscmg> [cid:19370283-4150-46ee-9244-193f0e5ba039] <https://www.instagram.com/ethos.cmg/>  [linkedin-icon_64x64] <https://www.linkedin.com/company/ethos-career-management-group/>  [cid:36626ecd-1af3-4362-8ce6-8a979bd259c8] ***@***.***>

ETHOS acknowledges with gratitude all the First Nations on whose traditional and unceded lands we work and provide service; in particular, the Snuneymuxw, Stz'uminus and Quw’utsun peoples, on whose lands our offices are located.

If you receive this e-mail in error, please notify the sender by reply e-mail and delete and destroy the message.

ü Please consider the environment before printing this email.



________________________________

**Comment by besessener** [comment]
Whoopsie, looks like there was an incompatibility. I only wanted to use Java 8 features but somehow a small Java 15 feature made it into the plugin and my CI was not checking that. I replaced the function with something older and also improed my pipeline.

v0.2.3 is released with this fix: https://github.com/Qytera-Gmbh/JMeterHARImporterPlugin/releases/tag/v0.2.3

I will leave a message and close the issue as soon as the new package is available in the plugins manager.

**Comment by gjhethos** [comment]
Hello Mathias:

Thank you so much for this.  I've manually added the plugin to my Jmeter, and it now loads properly.

I copy and pasted the transaction into a thread group and was able to use it to run a performance test.

Sincerely,
Gord


Gord Holtslander (he/him/his)

Systems Administrator

[cid:53397317-1273-45b8-b5f4-b02c722876c3]<https://www.ethoscmg.com/>    [cid:a3c12cae-87f1-4946-8319-6ec552305454]

202-155 Skinner Street, Nanaimo, BC, V9R 5E8

***@***.***

ethoscmg.com<https://www.ethoscmg.com/>

[facebook-icon_64x64]<https://www.facebook.com/ethoscmg> [cid:30fc4526-2070-44a2-91c3-bca7b7007951] <https://www.instagram.com/ethos.cmg/>  [linkedin-icon_64x64] <https://www.linkedin.com/company/ethos-career-management-group/>  [cid:ede42552-9eb0-4c85-aa4e-8b5adf225eda] ***@***.***>

ETHOS acknowledges with gratitude all the First Nations on whose traditional and unceded lands we work and provide service; in particular, the Snuneymuxw, Stz'uminus and Quw’utsun peoples, on whose lands our offices are located.

If you receive this e-mail in error, please notify the sender by reply e-mail and delete and destroy the message.

ü Please consider the environment before printing this email.



________________________________

**Comment by besessener** [comment]
Glad to hear that it helped. It is also officially available from plugin manager now: https://github.com/undera/jmeter-plugins/pull/664
